### ISSUE TITLE
Why another?

### ISSUE THREAD

**Issue by arielpts** [zeroXten/logstash_forwarder#1]
There's a good one:
https://github.com/phildougherty/chef-logstash-forwarder

Why not improve it?

**Comment by zeroXten** [comment]
To be honest, I didn't see that one as it wasn't published on community.opscode.com

However, at it isn't there yet, I'll continue to use mine as berkshelf is a pain to use when not talking to the opscode site (end up having to copy github urls around everywhere).

I'll create an issue for them to publish it and I'll test it with my chef_vault_pki cookbook.

Thanks for the feedback.

**Comment by zeroXten** [comment]
Or not.. issues seem to be disabled.

**Comment by BarthV** [comment]
This issue can be closed since @phildougherty chef-logstash-forwarder is not updated since 2013.

also we got another cookbook duplicate issue here : https://github.com/parallels-cookbooks/cookbook-logstash-forwarder/issues/2

Maybe @Kasen can tell us his motivations here too :D ?

**Comment by zeroXten** [comment]
This cookbook has been deprecated in favour of https://github.com/parallels-cookbooks/cookbook-logstash-forwarder
