### ISSUE TITLE
Cleaning up git history would make it easier to contribute pull requests

### ISSUE THREAD

**Issue by mcamou** [zeroXten/logstash_forwarder#2]
I just did a fork and cloned it to my machine. Even though you deleted the binary packages from the repository, they are still there in history, so clone takes a LONG time. It would be much better if you could remove them from history.

**Comment by zeroXten** [comment]
This cookbook has been deprecated in favour of https://github.com/parallels-cookbooks/cookbook-logstash-forwarder
